buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.jruby-gradle:jruby-gradle-plugin:2.0.0"
    }
    configurations.classpath {
        resolutionStrategy {
            // Avoid build error with version conflicts
            force 'org.ysb33r.gradle:grolifant:0.12.1'
            dependencySubstitution {
                substitute module('com.burgstaller:okhttp-digest') with module('io.github.rburgst:okhttp-digest:3.1.1')
            }
        }
    }
}

apply plugin: 'com.github.jruby-gradle.base'
apply plugin: 'java'
apply plugin: 'checkstyle'

import com.github.jrubygradle.JRubyExec

group 'com.github.ttksm'
version '0.3.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

configurations {
    provided
}

dependencies {
    compile 'org.embulk:embulk-core:0.11.5'
    provided 'org.embulk:embulk-core:0.11.5'
    compile 'software.amazon.awssdk:s3:2.17.282'
    testCompile 'org.junit.jupiter:junit-jupiter:5.+'
    testCompile 'org.mockito:mockito-core:3.+'
    testCompile 'org.mockito:mockito-junit-jupiter:3.+'
    testCompile 'org.embulk:embulk-core:0.11.5'
    compile 'software.amazon.awssdk:bom:2.17.282'
    compile 'software.amazon.awssdk:sso:2.17.282'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:unchecked'
    options.encoding = 'UTF-8'
}

task classpath(type: Copy, dependsOn: 'jar') {
    doFirst {
        file('classpath').deleteDir()
    }
    from (configurations.runtime - configurations.provided + files(jar.archivePath))
    into 'classpath'
}
clean {
    delete 'classpath'
}

checkstyle {
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
    toolVersion = '6.14.1'
}
checkstyleMain {
    configFile = file("${project.rootDir}/config/checkstyle/default.xml")
    ignoreFailures = true
}
checkstyleTest {
    configFile = file("${project.rootDir}/config/checkstyle/default.xml")
    ignoreFailures = true
}
task checkstyle(type: Checkstyle) {
    classpath = sourceSets.main.output + sourceSets.test.output
    source = sourceSets.main.allJava + sourceSets.test.allJava
}

task gem(type: JRubyExec, dependsOn: ['build', 'gemspec', 'classpath']) {
    jrubyArgs '-S'
    script 'gem'
    scriptArgs 'build', 'build/gemspec'
    doLast {
        if (!version.endsWith('-SNAPSHOT')) {
            copy {
                from "${project.name}-${project.version}.gem"
                into 'pkg'
            }
        }
    }
}

task gemspec {
    doLast {
        file('build/gemspec').write($/
Gem::Specification.new do |spec|
  spec.name          = "${project.name}"
  spec.version       = "${project.version}"
  spec.authors       = ['Toshihiro Takushima']
  spec.summary       = %[Amazon S3 output plugin for Embulk]
  spec.description   = %[Stores files on Amazon S3 using aws-sdk-java-v2.]
  spec.email         = ['ttksm.git@gmail.com']
  spec.licenses      = ['MIT']
  spec.homepage      = 'https://github.com/ttksm/embulk-output-s3v2'

  spec.files         = `git ls-files`.split("\n") + Dir['classpath/*.jar']
  spec.test_files    = spec.files.grep(%r'^(test|spec)/')
  spec.require_paths = ['lib']
end
/$)
    }
}
